FROM node:22

# Update package lists and install required dependencies
RUN apt-get update && \
    apt-get install -y build-essential python3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application source code
COPY . .

# Expose the application's port
EXPOSE $SERVER_PORT

# Default command to run the application
CMD ["npm", "start"]
